apiVersion: apps/v1
kind: Deployment
metadata:
   name: html-app
spec:
   replicas: 2
   selector:
      matchLabels:
         app: html
   template:
      metadata:
         Labels:
            app: html
   specs:
      containers:
       - name: nginx
         image: acr1123-dme9fveuabfagfha.azurecr.io/html-app:lates
         ports:
          - containerPort: 80
