apiVersion: apps/v1
kind: Deployment
metadata:
  name: gha-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gha
  template:
    metadata:
      labels:
        app: gha
    spec:
      containers:
      - name: gha-container
        image: ghademoacr123.azurecr.io/gha-app:latest
        ports:
        - containerPort: 80
