name: Build & Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2Ô∏è‚É£ Azure Login (Service Principal using creds JSON)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3Ô∏è‚É£ Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # 4Ô∏è‚É£ Terraform Init
      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      # 5Ô∏è‚É£ Terraform Plan (VERY IMPORTANT for visibility)
      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform

      # 6Ô∏è‚É£ Terraform Apply (creates AKS)
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform

      # 7Ô∏è‚É£ Login to ACR
      - name: Login to ACR
        run: az acr login --name acr1123

      # 8Ô∏è‚É£ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t acr1123-dme9fveuabfagfha.azurecr.io/html-app:latest app

      # 9Ô∏è‚É£ Push Docker image
      - name: Push Docker image
        run: |
          docker push acr1123-dme9fveuabfagfha.azurecr.io/html-app:latest

      # üîü Set AKS context (uses AKS created by Terraform)
      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: AKS-RG
          cluster-name: tf-cluster

      # 1Ô∏è‚É£1Ô∏è‚É£ Deploy application to AKS
      - name: Deploy app
        run: kubectl apply -f k8s/
